sudo: true
services:
  - redis-server
jdk:
  - oraclejdk8
language: clojure

addons:
  apt:
    sources:
      - elasticsearch-2.x
    packages:
      - elasticsearch
    services:
      - elasticsearch

install: true

script: 
  - curl http://127.0.0.1:9200/
  - lein do clean, compile, midje :filter -integration, midje :redis, midje :elasticsearch
